### ISSUE TITLE
Support TB 115.0

### ISSUE THREAD

**Issue by jvacek** [Mikaleb/Thunvatar#8]
Hey @Mikaleb, I've stumbled upon this online as I was setting up tb115 due to the hype, and I was sad to see this was not compatible with it.

Is there a chance to get an update which would support it including the card view? would be grand, thanks!

**Comment by Mikaleb** [comment]
Woah sorry I just saw your comment !  I'll try to make it work with tb115 if they finally updated their documentation, pulling out this one was hard enough.

Looking into it

**Comment by Mikaleb** [comment]
Looks like it's not possible, closing for now, contributions welcome !
